
appname = TravelSphere
httpport = 8080
runmode = dev
sessionon = true
sessionprovider = memory
sessionname = travelsphere_session
sessiongcmaxlifetime = 86400
copyrequestbody = true
EnableDocs = false